### ISSUE TITLE
Laravel 5.1?

### ISSUE THREAD

**Issue by ronnorthrip** [duxet/laravel-rethinkdb#11] opened 2015-11-18 14:24 UTC
Are you working on moving this to Laravel 5.1?

**Comment by danwilliams** [comment] 2015-11-20 15:01
I've submitted a pull request to bring in my branch that fixes it to work with Laravel 5.1. You can find the branch here for now: https://github.com/danwilliams/laravel-rethinkdb

**Comment by danwilliams** [comment] 2015-11-21 10:51
My pull request has been approved and my fixes are now on master in the official repository. You should find it works with Laravel 5.1 for you now.

**Comment by ronnorthrip** [comment] 2015-12-04 00:45
Thank You Dan!

**Comment by karllhughes** [comment] 2015-12-18 19:22
Confirmed. This package works for me on Laravel 5.1 as well. Can we close this issue?

**Comment by duxet** [comment] 2015-12-19 02:50
If there is no other compatibility issues, then yes @karllhughes :)

**Closed as completed by duxet** 2015-12-19 02:50 UTC
